In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Datasets/Restaurant Review-bow/Restaurant_Reviews.tsv",sep="\t")     #(1000, 2)

In [ ]:
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
#data preprocessing -
#  1 making all letters in lowercase (to avoid duplicacy of word like-Love and love -it creates unnecessary cols due to which problem creates while encoding)
#  2 remove all stopwards(unnecessary words wich have no connection with reviews)
#  3 making rootwords of words(ex. loving--love)

In [ ]:
import re          #regular expression

In [ ]:
import nltk

In [ ]:
nltk.download("stopwords")     #stopwords is a inbuilt list that contains unnecessary words

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
stopwords=nltk.corpus.stopwords.words('english') #we can take any language
len(stopwords)


179

In [ ]:
list1=[ 
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under', 
 'no',
 'nor',
 'not', 
 'don',
 "don't", 
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [ ]:
len(list1)

44

In [ ]:
179-44

135

In [ ]:
for word in stopwords:        #some negative words are imp if we remove them from sentence it changes meaning of sentence therefore we delete them from list
  if word in list1:
    stopwords.remove(word)
print(stopwords)              #list of unnecessary words

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'in', 'out', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 

In [ ]:
len(stopwords)

135

In [ ]:
stemmer = nltk.stem.PorterStemmer()  #root word dictionary
#findrootword of running
stemmer.stem('running')

'run'

**Data** **Preprocessing**

In [ ]:
def preprocess(review):        #review is a single sentense       "Wow... Loved this place."
    review = review.lower()    #make all letters of words in lowercase     "wow... loved this place."
    review = re.sub('[^a-z]',' ',review)        #"wow loved this place"                 #remove dots               
    #except a to z it will remove all other by "space" for more info "https://www.w3schools.com/python/python_regex.asp" cap=^ means except a to z  .syntax--first=not to be remove frm words,second=remove with,third=which sentence
    words = review.split()      
    #splits with space but remove unnecessary spaces in between words,take single space   ["wow" ,"loved" ,"this" ,"place"]....
    final_words = [stemmer.stem(word) for word in words if not word in stopwords]   #["wow" ,"love" ,"place"]
    #rooting those words which are not in stopwords       
    #list of words with modification in rootword and selecting those words which are not in stopwords means just remove unnnecessary info 
    return ' '.join(final_words)         #wow love place 
    # join list with space

In [ ]:
preprocess('Crust is not good.')

'crust not good'

In [ ]:
df["Review"]=df["Review"].apply(preprocess)    #apply process function on review column and save in same it gives processed review

In [ ]:
df["Review"]

0                                         wow love place
1                                         crust not good
2                                 not tasti textur nasti
3      stop late may bank holiday off rick steve reco...
4                             select on menu great price
                             ...                        
995                        think food flavor textur lack
996                               appetit instantli gone
997                 overal not impress would not go back
998    whole experi underwhelm think go ninja sushi n...
999    hadn wast enough life pour salt wound draw tim...
Name: Review, Length: 1000, dtype: object

# **Converting word to numeric format**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer()
vectorizer.fit(df["Review"])   #.fit counts unique words

CountVectorizer()

In [ ]:
len(vectorizer.get_feature_names())          #vectorizer.get_feature_names() list of unique words

1584

In [ ]:
bow_table = vectorizer.transform(df["Review"])  
# making 1584 cols and putting 1 in the cell where given word in sentense is present else putting 0
#this case "0's" becomes very much more than 1's ..and creating problem of sparse...therefore we convert it in numpy array

In [ ]:
X_train=bow_table.toarray()
y_train=df["Liked"]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=50, random_state=10)
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50, random_state=10)

In [ ]:
#0 for positive review 1 for negative reiew

In [ ]:
def predict_review(review):
    review = preprocess(review)     #applying above prepprocessing function
    X_test = vectorizer.transform([review])  #transformin it int 0,1 matrix
    return model.predict(X_test)

In [ ]:
predict_review('cofee is not good')

array([0])

In [ ]:
predict_review('Puri is good but jamun was too bad')

array([0])

In [ ]:
predict_review('Service was good.')

array([1])

In [ ]:
predict_review('Puri is not good')

array([0])